# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  lint:
    name: "Lint"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-binary:
          - "php7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Validate Composer"
        run: "composer validate --strict"

      - name: "Cache dependencies"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "${{ matrix.php-binary }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "${{ matrix.php-binary }}-composer-"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Lint"
        run: "vendor/bin/phing"
