dist: xenial
language: php

stages:
  - test
  - name: phar-test
    if: branch = master && type = push
  - name: phar-push
    if: branch = master && type = push

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

env:
  global:
    secure: 52I5lvhMQp3UpfrwkV4cfb2p2g0RdTTxEUddyv/VmzTiJMEZ67j7QrOvzgmC8hY1VJdXN2zXZuWGbtooxGrjDoiSHRxGwDOxzEucbVWqMQ4vBSBJ3zoqScPOphuXMlTcTL+Z2AcgnYDAXOOM340iZRZbErlgMt5XULVbkJvt1qgW2/w9Rc4k6Oaih5iZA4a8cA/81PuiM/e6/lakP/+rdhhQHG7AKRms+N4RM+51WMmsITffb+fZoMA4oQtp5tK391Hev0J9muJZbqdmQl+3f12vI0eDLr2V6bNtr3KNV/Xx58Pm4Eg69RjObNIdJF5fD+e02+eqHyfdEX3nRBh2b0pzCzX+eaAn6Q7eVdy387Qagy7dI5gBZ3yXX2CCYXdHVKJfe6sS7CZO00I3KFv0rnwuWHNwoU5mQx+Zib5c0x5ttWFaWOtcpRN5oSuclfZPqSJpd+P/5BB+iKlrpwRU2kN5//7K4yE9jFgXGDMJgD2DXqoQxe5hOVk6dPQYg1sKd+iAUt+iV2uU9wFRJ/PlW16ilPTXnhpoJHRVmeN73Q2fkX112ueya99Tariolw0FJWVle5oYJP+PRszs9owKkOnv/CJ2li5LB1fVt/xry8x35K3dAT4OMGur2JJksAjfZJ6ADKkK8VRbg3Lzh3M1klbRw7XD8TBxfhyRVr+SD70=
matrix:
  allow_failures:
    - php: master

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

install:
  - composer update --no-interaction

script:
  - vendor/bin/phing

jobs:
  include:
    - stage: phar-test
      script:
        - git clone https://github.com/phpstan/phpstan-compiler && cd phpstan-compiler && ./run-e2e-tests.sh $TRAVIS_COMMIT
    - stage: phar-push
      script:
        - |
          git clone https://github.com/phpstan/phpstan-compiler && \
          composer install --working-dir=phpstan-compiler && \
          php phpstan-compiler/bin/compile $TRAVIS_COMMIT && \
          git clone https://${GITHUB_TOKEN}@github.com/phpstan/phpstan.git > /dev/null 2>&1 && \
          cp phpstan-compiler/tmp/phpstan.phar phpstan/phpstan.phar && \
          cp phpstan-compiler/tmp/phpstan.phar phpstan/phpstan && \
          cd phpstan && \
          git config user.email "travis@travis-ci.org" && \
          git config user.name "Travis CI" && \
          git add phpstan phpstan.phar && \
          git commit -m "Updated PHPStan to commit ${TRAVIS_COMMIT}" && \
          git push --quiet origin master

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
