dist: xenial
language: php

stages:
  - test
  - name: phar
    if: branch = master && type = push

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

env:
  global:
    secure: "EpvZZ1v6JvefnfhgYm3Y2WprJxjgr6zDw2FJs+WISEtd1PHJToFJOE59vW7DRTcr5ycR4jrHyANqqIJWbH1k3A3wuyavmkissNKHbFK6vmLtAC9TuI/x5zBd+/T5yQ6i6uBe43nDzbkrQDYtGyNMdn1FXhWV9Z/hNCZ6uD0aiO5+d49NFJoexUOt3+LCxrZAGCCsm49KYRff/62QxO2Wajlfdhx+PLO0igY/i9N3oUQoVfbBEbP1ZSAPLv7ZkZGL4XdMMYEGYqnOeMWk39MYID34RmCYteWRfED4oqYbi4rzOpW8YeA/YkuHGThIykSLBrjdAfwUpekVEAI9r1gdrh91Gkpm/W/trFygdfI2gqev5GVjbYgmKQMm50l1W8wiD+Tb+AMUIttEXGjgwd+K2rn1RBHjM+CjPEWWdppg/7OOYVIJg0gIr94TN2LCQWDfFN5SxIIf0BpQmWteGEPCDpxCc3jsjpaVFXQ2jrui69Pdjr8/u7XCisQD9zpn4sQ43GZkdHC4rGOoBrjXQDWMB/LZyYNymJ6fkkuceqSgn6vDyBEkp9UBR1CIv4P8Ray86qEPodDFbPZMVX2JqDwUHMH3HVl4FINPYtVW3/VNUK7VihKd33+AjoX7anRTeq0T8jXUT4IF6tAxbO4DaDBB4XjQ3vCBDH15WxwIxy81KKA="
matrix:
  allow_failures:
    - php: master

before_script:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi

install:
  - composer update --no-interaction

script:
  - vendor/bin/phing

jobs:
  include:
    - stage: test
      php: 7.3
      name: Compiler tests
      script:
        - |
          cd compiler && \
          composer install --no-interaction && \
          vendor/bin/phpunit -c tests/phpunit.xml tests && \
          ../bin/phpstan analyse -l 8 src && \
          ./run-e2e-tests.sh
    - stage: phar
      php: 7.3
      script:
        - |
          composer install --working-dir=compiler && \
          php compiler/bin/compile && \
          git clone https://${GITHUB_TOKEN}@github.com/phpstan/phpstan.git phpstan-dist > /dev/null 2>&1 && \
          cp tmp/phpstan.phar phpstan-dist/phpstan.phar && \
          cp tmp/phpstan.phar phpstan-dist/phpstan && \
          cd phpstan-dist && \
          git config user.email "travis@travis-ci.org" && \
          git config user.name "Travis CI" && \
          git add phpstan phpstan.phar && \
          git commit -m "Updated PHPStan to commit ${TRAVIS_COMMIT}" && \
          git push --quiet origin master

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
