# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  lint:
    name: "Lint"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-binary:
          - "php7.1"
          - "php7.2"
          - "php7.3"
          - "php7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Validate Composer"
        run: "composer validate --strict"

      - name: "Cache dependencies"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "${{ matrix.php-binary }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "${{ matrix.php-binary }}-composer-"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Composer Normalize"
        run: "vendor/bin/phing composer-normalize-check"

      - name: "Composer Require Checker"
        run: "vendor/bin/phing composer-require-checker"

      - name: "Lint & Coding Standard"
        run: "vendor/bin/phing lint && vendor/bin/phing cs"

      - name: "Tests"
        run: "vendor/bin/phing tests"

      - name: "PHPStan"
        run: "vendor/bin/phing phpstan"

      - name: "PHPStan with static PHP-Parser"
        run: "vendor/bin/phing phpstan-static-php-parser"
